"""add registration_number and password_hash to Doctor model

Revision ID: 26aeb90c2606
Revises: 18b13767de4a
Create Date: 2024-11-13 18:05:52.115913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26aeb90c2606'
down_revision = '18b13767de4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_number', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint('uq_doctor_registration_number', ['registration_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint('uq_doctor_registration_number', type_='unique')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('registration_number')

    # ### end Alembic commands ###
