"""add email to doctor model

Revision ID: 7a272adce4ec
Revises: 66a78da119db
Create Date: 2024-11-14 23:12:48.727104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a272adce4ec'
down_revision = '66a78da119db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_doctor_email'), ['email'], unique=True)

    with op.batch_alter_table('receptionist', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_receptionist_employee_id', ['employee_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receptionist', schema=None) as batch_op:
        batch_op.drop_constraint('uq_receptionist_employee_id', type_='unique')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
