"""add email to receptionist model

Revision ID: 9ca391689a72
Revises: 7a272adce4ec
Create Date: 2024-11-14 23:32:30.049158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca391689a72'
down_revision = '7a272adce4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receptionist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_receptionist_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receptionist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receptionist_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
